FROM openjdk:8-jdk

EXPOSE 8080

COPY target/employee-management-system-0.0.1-SNAPSHOT.jar employee-management-system-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","employee-management-system-0.0.1-SNAPSHOT.jar"]